excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jhu-cte.github.io
title: CTE
tagline: Center for Technology in Education
description: Center for Technology in Education
paginate: 5
